language: python
sudo: false
cache:
  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/buildout-cache
python:
  - 2.7
services:
    - xvfb
addons:
  apt:
    packages:
    - libpcre3
    - libpcre3-dev
    - libssl-dev
    - libexpat1-dev
    - gnuplot
    - libgdk-pixbuf2.0-0
    # needed libs for chromedriver
    - libnss3-dev
    - libgconf-2-4
  chrome: stable
before_script:
  ### Install the latest chromedriver manually from https://sites.google.com/a/chromium.org/chromedriver/downloads
  # NB: must be setuid root to move this executable
  #     => commented out, since the chrome browser exits unexpeted and the robot tests are not passing anyhow
  - wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/
  ###
  #- export DISPLAY=99.0
  #- sh -e /etc/init.d/xvfb start
before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/buildout-cache/{eggs,downloads}
  - echo "[buildout]" > $TRAVIS_BUILD_DIR/default.cfg
  - echo "download-cache = $TRAVIS_BUILD_DIR/buildout-cache/downloads" >> $TRAVIS_BUILD_DIR/default.cfg
  - echo "eggs-directory = $TRAVIS_BUILD_DIR/buildout-cache/eggs" >> $TRAVIS_BUILD_DIR/default.cfg
  - virtualenv .
  - source bin/activate
  - bin/pip install --upgrade pip setuptools zc.buildout
  - bin/pip install simplejson xlsxwriter
  - mkdir -p src/
  - git clone https://github.com/BaobabLims/bika.lims.git src/
  - git clone https://github.com/BaobabLims/graphite.theme.git src/ 
install:
  - bin/buildout -n -t 3 -c travis.cfg 
script:
  - bin/test -m baobab.lims --layer=baobab.lims.testing.BaobabTestingLayer:site_setup
  
